### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by chivay**

### CODE REVIEW

**Comment by msm-code** [comment]
How did it work before / how does it work now / what does it change?

Python modules are hard, but FWIW this code kinda works (but I'm running it as a usual python script).

Anyway, IMO we should scrap this script and move this (very simple) utlility to ursadb core - thoughts?

**Comment by chivay** [comment]
After installing the package with  `pip install .` and running `ursaclient` (from PATH) there was an import error :thinking:

**Comment by msm-code** [comment]
Yah, that's what I've thought :thinking: .

Yeah, but on the other hand this code now won't run as script, right? So for example README.md in mquery becomes obsolete:

```
> cat README.md | grep cli
After you start the system, you should index some files. Use ursadb-cli:
sudo docker-compose run ursadb-cli tcp://ursadb:9281

> sudo docker-compose run ursadb-cli tcp://ursadb:9281
Traceback (most recent call last):
  File "ursadb/ursaclient.py", line 5, in <module>
    from ursadb.terminal import setup_terminal
ModuleNotFoundError: No module named 'ursadb'
```

Not necessarily a problem, but the Dockerfile in this repo needs to be updated accordingly

**Review by msm-code — CHANGES_REQUESTED** [review]
Please also update the dockerfile

**Comment by chivay** [comment]
```
(venv) [chivay@arnold ursadb]$ python ursaclient.py
[ ] Connecting: tcp://localhost:9281
[!] Connection failed: Resource temporarily unavailable
```
works for me :thinking: 
oh, you meant without installing  :thinking:

**Comment by msm-code** [comment]
Yeah, like a (current) dockerfile does:

```
FROM python:3.6

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

COPY . /app
WORKDIR /app
ENTRYPOINT ["/usr/local/bin/python3", "-m", "ursadb"]
```

As I've said above, I'd gladly get rid of this script from hell and merge it with ursadb core - but as long as we have it, it should work with mquery's default docker-compose.

**Review by msm-code — APPROVED** [review]
I like this change, we're saving bytes

**Pull request merged**
